.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)syslog.conf.5	8.1 (Berkeley) 6/9/93
.\"
.Dd от 10 декабря, 2020 г.
.Dt SYSLOG.CONF 5
.Os
.Sh МЯ
.Nm syslog.conf
.Nd
.Xr syslogd 8
файл конфигурации
.Sh ОПИСАНИЕ
Файл
.Nm
является конфигурационным файлом для
.Xr syslogd 8
программы.
Он состоит из
блоков строк, разделенных
.Em program ,
.Em hostname
или
.Em спецификации фильтров, основанные на свойствах
(разделители отображаются отдельно в их строках),
причем каждая строка содержит два поля: 
.Em selector
поле, в котором указываются типы сообщений и приоритеты, к которым
применяется строка, и
.Em action
поле, в котором указывается действие, которое необходимо предпринять, если получено сообщение
.Xr syslogd 8
полученные данные соответствуют критериям отбора.
Поле
.Em selector
отделено от поля
.Em action
одним или несколькими символами табуляции или пробелами.
.Pp
специальное ключевое слово
.Em include
keyword может использоваться для включения всех файлов с именами, оканчивающимися на '.conf' и не
начинающиеся с'.' содержится в каталоге, следующем за ключевым словом.
Это ключевое слово можно использовать только в файле конфигурации первого уровня.
.Pp
Обратите внимание, что если вы используете пробелы в качестве разделителей, то ваш
.Nm
может быть несовместим с другими Unice или Unix-подобными системами.
Эта функциональность была добавлена для упрощения настройки
(e.g.,\& можно вырезать и вставить в
.Nm ) ,
и чтобы избежать возможных ошибок.
Однако это изменение сохраняет
обратную совместимость со старым стилем
.Nm
(i.e., tab characters only).
.Pp
Параметры
.Em selectors
кодируются как
.Em facility ,
периудом
.Pq Dq \&. ,
дополнительный набор флагов сравнения
.Pq Oo \&! Oc Op <=> ,
и как 
.Em level ,
без промежуточных пробелов.
Оба параметра
.Em facility
и параметры
.Em level
не чувствительны к регистру.
.Pp
Параметр
.Em facility
описывает часть системы, генерирующую сообщение, и является одним из
следующих ключевых слов:
.Cm auth , authpriv , console , cron , daemon , ftp , kern , lpr ,
.Cm mail , mark , news , ntp , security , syslog , user , uucp ,
и
.Cm local0
через
.Cm local7 .
Эти ключевые слова (за исключением знака) соответствуют
аналогичным
.Dq Dv LOG_
значения, указанные для
.Xr openlog 3
и
.Xr syslog 3
библиотечных процедур.
.Pp

.Em сравнительные флаги
может использоваться для точного указания того, что регистрируется в журнале.
По умолчанию используется сравнение
.Dq =>
(или, если вы больше предпочитаете,
.Dq >= ) ,
это означает, что сообщения от указанного параметра
.Em facility
список и
с уровнем приоритета, равным или превышающим
.Em level
будет занесен в журнал.
Флаги сравнения, начинающиеся с
.Dq Li \&!
будет перевернут их логический смысл.
Таким образом
.Dq !=info
означает все уровни, кроме информационного и
.Dq !notice
и им еют одно значение
.Dq <notice .
.Pp
Параметр
.Em level
описывает серьезность сообщения и является ключевым словом из
следующего упорядоченного списка (от верхнего к нижнему):
.Cm emerg , alert , crit , err , warning , notice , info
и
.Cm debug .
Эти ключевые слова соответствуют
похожим
.Dq Dv LOG_
значения, указанные для
.Xr syslog 3
библиотечных процедур.
.Pp
Каждый блок строк отделен от предыдущего блока символом
.Em program ,
.Em hostname
или
.Em property-based filter
specification.
Блок будет регистрировать только сообщения, соответствующие самым последним
.Em program ,
.Em hostname
и
.Em property-based filter
даны спецификации.
Таким образом, с помощью блока, который выбирает
.Ql ppp
в качестве
.Em program ,
непосредственно за ним следует блок, который выбирает сообщения из
.Em hostname
.Ql dialhost ,
второй блок будет регистрировать только сообщения
от
.Xr ppp 8
program on dialhost.
.Pp
A
.Em program
спецификация - это строка, начинающаяся с
.Ql #!prog
or
.Ql !prog
(первый предназначен для совместимости с предыдущим syslogd, если кто-то использует общий доступ
.Nm
к файлам, например)
и следующие блоки будут связаны с вызовами
.Xr syslog 3
из этой конкретной программы
A
.Em program
спецификация для
.Ql foo
также будет соответствовать любому сообщению, зарегистрированному ядром с префиксом
.Ql "foo: " .

.Ql #!+prog
или
.Ql !+prog
спецификация работает точно так же, как и предыдущая,
и
.Ql #!-prog
или
.Ql !-prog
спецификация будет соответствовать любому сообщению, кроме сообщений от этой
программы.
Может быть указано несколько программ, разделенных запятыми:
.Ql !prog1,prog2
сопоставляет сообщения из любой программы, в то время как
.Ql !-prog1,prog2
соответствует всем сообщениям, кроме сообщений от
.Ql prog1
or
.Ql prog2 .
.Pp
A
.Em hostname
спецификации формы
.Ql #+hostname
или
.Ql +hostname
означает, что к сообщениям
, полученным с указанного имени хоста, будут применены следующие блокировки.
В качестве альтернативы,
.Em hostname
спецификация
.Ql #-hostname
или
.Ql -hostname
приводит к применению следующих блоков к сообщениям
с любого хоста, кроме указанного.
Если имя хоста указано как
.Ql @ ,
будет использоваться локальное имя хоста.
Что касается спецификаций программы,
то для спецификаций имени хоста может быть указано несколько значений, разделенных запятыми.
.Pp
Спецификация
.Em property-based filter
это строка, начинающаяся с
.Ql #:
или
.Ql \&:
и следующие блоки будут применены только тогда, когда значение фильтра
будет соответствовать значению данного свойства фильтра.
См. раздел
.Sx PROPERTY-BASED FILTERS
для большей информации.
.Pp
A
.Em program ,
.Em hostname
либо
.Em property-based filter
спецификация может быть изменена путем указания
.Ql *
в качестве параметра.
.Pp
См.
.Xr syslog 3
для дальнейшего описания обоих
.Em facility
и
.Em level
ключевые слова и их значимость.
Предпочтительно, чтобы выбор был сделан на
.Em facility
скорее чем на
.Em program ,
поскольку последние могут легко изменяться в сетевой среде.
Однако в некоторых случаях соответствующий
.Em facility
просто напросто не существует.
.Pp
Если полученное сообщение соответствует указанному
.Em facility
и имеет указанный
.Em level
.Em (or a higher level) ,
и первое слово в сообщении после даты соответствует
.Em program ,
действие, указанное в
.Em action
поле будет использовано.
.Pp
Множество
.Em selectors
может быть задан для одного
.Em action
разделяя их точкой с запятой
.Pq Dq \&;
символами.
Однако важно отметить, что каждый
.Em selector
может изменять те, что предшествовали ему.
.Pp
Множество
.Em facilities
может быть задан для одного
.Em level
разделяя их точкой 
.Pq Dq \&,
символами.
.Pp
Звездочка
.Pq Dq *
может использоваться для указания всех
.Em facilities ,
всех
.Em levels ,
либо всех
.Em programs .
.Pp
Специальный
.Em facility
.Dq mark
получает сообщение с приоритетом
.Dq info
каждые 20 минут
(см.
.Xr syslogd 8 ) .
Это не включается с помощью
.Em facility
поле, отмеченное звездочкой.
.Pp
Специальный
.Em level
.Dq none
отключает определенный
.Em facility .
.Pp
Поле
.Em action
поле каждой строки указывает действие, которое должно быть предпринято, когда
.Em selector
в поле выбирается сообщение.
Существует пять форм:
.Bl -bullet
.It
в поле выбирается сообщение.
Существует пять форм.Путь к файлу (начинается с косой черты).
Выбранные сообщения будут добавлены в файл.
.Pp
Для обеспечения оперативной записи сообщений ядра на диск,
.Nm
вызывает
.Xr fsync 2
после записи сообщений из ядра.
Другие сообщения явно не синхронизируются.
Вы можете добавить к имени пути знак минус,
.Dq - ,
чтобы отказаться от синхронизации указанного файла после каждого сообщения ядра.
Обратите внимание, что вы можете потерять информацию, если система выйдет из строя
сразу после попытки записи.
Тем не менее, использование
.Dq -
эта опция может повысить производительность,
особенно если ядро регистрирует много сообщений.
.It
Имя хоста (которому предшествует 
.Pq Dq @
знак).
Выбранные сообщения пересылаются на
.Xr syslogd 8
программа на указанном хосте.
Если после двоеточия добавляется номер порта
.Pq Ql :\&
тогда этот порт будет использоваться в качестве порта назначения, 
а не как обычный порт системного журнала.
Можно использовать адреса IPv6, 
заключив часть адреса в
квадратные скобки
.Po
.Ql [\&
и
.Ql ]\&
.Pc .
.It
Список пользователей, разделенных запятыми.
Выбранные сообщения будут отправлены этим пользователям, 
если они вошли в систему.
.It
Отмечен звездочкой.
Выбранные сообщения будут отправлены всем зарегистрированным пользователям.
.It
Шкала верификации
.Pq Dq \&| ,
затем следует команда для отправки выбранных
сообщений.
Команда передается в
.Xr sh 1
для оценки могут использоваться обычные метасимволы оболочки или перенаправление ввода/вывода.
(Однако обратите внимание, что перенаправление
.Xr stdio 3
буферизованный вывод вызванной команды может привести к дополнительным задержкам
или даже к потере выходных данных в случае, если подпроцесс ведения журнала завершился с
сигналом.)
Сама команда выполняется с
.Em stdout
и
.Em stderr
перенаправлен на
.Pa /dev/null .
После получения
.Dv SIGHUP ,
.Xr syslogd 8
закроет канал связи с процессом.
Если процесс не завершился
добровольно, ему будет отправлено сообщение
.Dv SIGTERM
подайте сигнал после льготного периода продолжительностью до 60 секунд.
.Pp
Команда будет запущена только после поступления данных, которые должны быть переданы
в нее по конвейеру.
Если она завершилась позже, она будет перезапущена по мере необходимости.
Таким образом, если желательно, 
чтобы подпроцесс получал только одну строку ввода
(что может быть очень ресурсоемким, если
быстро поступает много сообщений), этого можно достичь, завершив работу только после одной строки
ввода.
При необходимости для этого может быть написана оболочка скрипта.
.Pp
Если команда не является полноценным конвейером, вероятно, полезно
запустить ее с помощью
.Em exec
чтобы вызывающий процесс оболочки не ждал завершения выполнения команды.
Внимание: процесс запускается под UID вызывающего процесса.
.Xr syslogd 8 ,
обычно это суперпользователь.
.El
.Pp
Пустые строки и строки, первый непустой символ которых является хэшем
.Pq Dq #
буквы игнорируются.
Если
.Ql #
помещается в середину строки, то
.Ql #
символ и остальная часть строки после него игнорируются.
Чтобы избежать придания особого значения, символ
.Ql #
символ может быть экранирован с помощью
.Ql \e ;
в этом случае предшествующий
.Ql \e
удаляется и
.Ql #
воспринимается как обычный символ.
.Sh ФИЛЬТРЫ, ОСНОВАННЫЕ НА СВОЙСТВАХ
.Em program ,
.Em hostname
спецификации выполняют фильтрацию точного соответствия только для явных полей.
Фильтры на основе свойств .Em
используйте подстроку и регулярные выражения (см.
.Xr re_format 7 )
сопоставление с различными атрибутами сообщения.
Спецификация фильтра начинается с
.Ql #:
или
.Ql \&:
за ними следуют три поля, разделенные запятыми
.Em property , operator , \&"value\&" .
Значение должно быть заключено в двойные кавычки.
Двойные кавычки и обратная косая черта должны быть экранированы обратной косой чертой.
.Pp
Следуя за
.Em properties
поддерживаются в качестве тестового значения:
.Pp
.Bl -bullet -compact
.It
.Ql msg
- body of the message received.
.It
.Ql programname
- program name sent the message
.It
.Ql hostname
- hostname of message's originator
.It
.Ql source
- an alias for hostname
.El
.Pp
Оператор определяет функцию сравнения между
.Em propertie's
 value against filter's value.
Возможные операторы:
.Pp
.Bl -bullet -compact
.It
.Ql contains
- true if filter value is found as a substring of
.Em property
.It
.Ql isequal
- true if filter value is equal to
.Em property
.It
.Ql startswith
- true if property starts with filter value
.It
.Ql regex
- true if property matches basic regular expression defined in filter value
.It
.Ql ereregex
- true if property matches extended regular expression defined in filter value
.El
.Pp
Оператор может иметь префикс в виде
.Pp
.Bl -bullet -compact
.It
.Ql \&!
- to invert compare logic
.It
.Ql icase_
- to make comparison function case insensitive
.El
.Sh IMPLEMENTATION NOTES
The
.Dq kern
функция обычно зарезервирована для сообщений, 
генерируемых локальным ядром.
Другие сообщения, регистрируемые с помощью функции
.Dq kern
обычно переводятся на язык facility
.Dq user .
Этот перевод можно отключить;
см.
.Xr syslogd 8
для деталей.
.Sh ФАЙЛЫ
.Bl -tag -width /etc/syslog.conf -compact
.It Pa /etc/syslog.conf
.Xr syslogd 8
файл конфигурации
.El
.Sh ПРИМЕРЫ
Файл конфигурации может выглядеть следующим образом:
.Bd -literal
# Log all kernel messages, authentication messages of
# level notice or higher, and anything of level err or
# higher to the console.
# Do not log private authentication messages!
*.err;kern.*;auth.notice;authpriv.none;mail.crit	/dev/console

# Log anything (except mail) of level info or higher.
# Do not log private authentication messages!
*.info;mail.none;authpriv.none		/var/log/messages

# Log daemon messages at debug level only
daemon.=debug						/var/log/daemon.debug

# The authpriv file has restricted access.
authpriv.*						/var/log/secure

# Log all the mail messages in one place.
mail.*							/var/log/maillog

# Everybody gets emergency messages, plus log them on another
# machine.
*.emerg							*
*.emerg							@arpa.berkeley.edu

# Root and Eric get alert and higher messages.
*.alert							root,eric

# Save mail and news errors of level err and higher in a
# special file.
uucp,news.crit						/var/log/spoolerr

# Pipe all authentication messages to a filter.
auth.*					|exec /usr/local/sbin/authfilter

# Log all security messages to a separate file.
security.*						/var/log/security

# Log all writes to /dev/console to a separate file.
console.*						/var/log/console.log

# Save ftpd transactions along with mail and news
!ftpd
*.*							/var/log/spoolerr

# Log ipfw messages without syncing after every message.
!ipfw
*.*							-/var/log/ipfw

# Log ipfw messages with "Deny" in the message body.
:msg, contains, ".*Deny.*"
*.*							/var/log/ipfw.deny

# Reset program name filtering
!*

# Log messages from bird or bird6 into one file
:programname, regex, "^bird6?$"
*.*							/var/log/bird-all.log

# Log messages from servers in racks 10-19 in multiple locations, case insensitive
:hostname, icase_ereregex, "^server-(dcA|podB|cdn)-rack1[0-9]{2}\\..*"
*.*							/var/log/racks10..19.log
.Ed
.Sh СМОТРЕТЬ ТАКЖЕ
.Xr syslog 3 ,
.Xr syslogd 8
.Sh ОШИБКИ
Последствия множественных
.Em selectors
иногда они не обладают интуицией.
Например
.Dq mail.crit,*.err
выберет
.Dq mail
сообщения объекта на уровне
.Dq err
или выше, а не на уровне
.Dq crit
или выше.
.Pp
Обратите внимание, что в сетевых средах не все операционные системы
реализуют одинаковый набор функций.
Функции
authpriv, cron, ftp, и ntp, которые известны для данной реализации, 
могут отсутствовать в целевой системе.
Что еще хуже, DEC UNIX uses
средство под номером 10 (которое в данной реализации является authpriv) для
регистрации событий в своей файловой системе AdvFS.
