.\" Copyright (c) 1985, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     from: @(#)ttys.5	8.1 (Berkeley) 6/4/93
.\" "
.Dd От 1 июня, 2021 г.
.Dt TTYS 5
.Os
.Sh ИМЯ
.Nm ttys
.Nd информация об инициализации терминала
.Sh ОПИСАНИЕ
Файл
.Nm
содержит информацию который используется различными подпрограммами для инициализации
и контроля использования специальных файлов терминала.
Псевдотерминалы (см.
.Xr pts 4 )
отсутствуют в списке.
Эта информация считывается с помощью
.Xr getttyent 3
библиотечные процедуры.
Есть одна строка в 
.Nm
файле на каждое специальное устройство.
Поля разделены символами табуляции и/или пробелами.
Поля, состоящие более чем из одного слова, должны быть заключены в двойной
цитаты (``"'').
Пустые строки и комментарии могут появляться в любом месте файла; комментарии
разделяются хэш-метками (``#'') и новыми строками.
Все неуказанные поля будут иметь значение null по умолчанию.
.Pp
Первое поле обычно
является именем специального файла терминала в том виде, в каком он был найден в
.Pa /dev .
Однако это может быть любая произвольная строка
, если соответствующая команда не связана с командой tty.
.Pp
Второе поле файла является командой для выполнения строки,
обычно
.Xr getty 8 ,
который инициализирует и открывает строку, устанавливая скорость, ожидая
ввода имени пользователя и выполняя
.Xr login 1
программу.
Однако это может быть любая желаемая команда, например
, запуск эмулятора терминала window системы или какого-либо другого
daemon процесса, и может содержать несколько слов, если заключена в кавычки.
.Pp
Третье поле - это тип терминала, обычно подключаемого к этой
tty строке, обычно тот, который находится в
.Xr termcap 5
файле базы данных.
Переменная среды
.Ev ОПРЕДЕЛЕНИЕ
инициализируется значением
либо
.Xr getty 8
либо
.Xr login 1 .
.Pp
В оставшихся полях установлены флажки в
.Fa ty_status
входе (см.
.Xr getttyent 3 ) ,
указывает процесс оконной системы, который
.Xr init 8
будет поддерживаться для терминальной строчки, необязательно определять
тип tty (будь то dialin, сетевой или какой-либо другой)
или указывать
имя группы tty, которое позволяет использовать базу данных классов входа (см.
.Xr login.conf 5 )
чтобы обращаться ко многим ttys как к группе, выборочно разрешать или
запрещать доступ, а также включать или отключать средства учета для
ttys как группы.
.Pp
В качестве значений флага используются строки ``on'' и ``off'' учитывайте, что
.Xr init 8
должен (не должен) выполнять команду, указанную во втором поле.
``onifconsole'' приведет к включению этой строки тогда и только тогда, когда это
активное консольное устройство ядра (это эквивалентно``on'' в данном случае).
Флаг ``onifexists'' приведет к включению этой строки, тогда и только
тогда, если имя существует. 
Если имя начинается с ``/'', оно будет считаться абсолютным
путем.
В противном случае оно считается путем относительно к
.Pa /dev .
Флаг ``secure'' (если консоль включена) позволяет пользователям с
uid равным 0 входить в систему по
этой строке.
Флаг ``dialup'' указывает, что запись tty описывает
строку набора номера, и ``network'' является устаревшим и ничего не дает.
Любая из этих строк также может быть указана в поле тип терминала.
За строкой ``window='' может следовать заключенная в кавычки командная
строка, которая выполнит
.Xr init 8

.Em перед
запуском команды, указанной во втором поле.
.Pp
За строкой ``group=''может следовать название группы, состоящее из
буквенно-цифровых символов, которые могут использоваться
.Xr login.conf 5
для обозначения множества строк tty как группы, чтобы включить или отключить средства доступа
и учета.
Если группа не указана, то tty становится членом группы
"none".
Для обеспечения обратной совместимости, ``group='' должен отображаться последним в
строке, непосредственно перед необязательным комментарием.
.Pp
Как второе поле, так и любая команда, указанная с помощью ``window=''
будет разбита на слова и выполнена с использованием
.Xr execve 2 .
Слова разделяются любыми комбинациями символов табуляции и пробелов.
Аргументы, содержащие пробелы, должны быть заключены в одинарные кавычки
.Pq Li ' .
Обратите внимание, что глобализация в стиле оболочки или другая замена переменных не происходит.
.Sh ФАЙЛЫ
.Bl -tag -width /etc/ttys -compact
.It Pa /etc/ttys
.El
.Sh ПРИМЕРЫ
.Bd -literal
# root login on console at 1200 baud
console	"/usr/libexec/getty std.1200"	vt100	on secure
# dialup at 1200 baud, no root logins
ttyd0	"/usr/libexec/getty d1200"	dialup	on group=dialup	# 555-1234
# Mike's terminal: hp2621
ttyh0	"/usr/libexec/getty std.9600"	hp2621-nl	on group=dialup	# 457 Evans
# John's terminal: vt100
ttyh1	"/usr/libexec/getty std.9600"	vt100	on group=dialup		# 459 Evans
# terminal emulate/window system
ttyv0	"/usr/local/bin/xterm -display :0"	xterm	on window="/usr/local/bin/X :0"
.Ed
.Sh SEE ALSO
.Xr login 1 ,
.Xr getttyent 3 ,
.Xr nmdm 4 ,
.Xr uart 4 ,
.Xr ucom 4 ,
.Xr gettytab 5 ,
.Xr login.conf 5 ,
.Xr termcap 5 ,
.Xr getty 8 ,
.Xr init 8 ,
.Xr pam_securetty 8 ,
.Xr pstat 8
.Sh ИСТОРИЯ
A
.Nm
файл появился в
.At v6 .
